[package]
name = "logging_macro"
version = "0.9.8"
authors = ["Noah Santschi-Cooney <noah@santschi-cooney.ch>"]
edition = "2024"

[lib]
proc-macro = true
doctest = false

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = [ "full" ] }

[lints.clippy]
missing_const_for_fn = "warn"
